module Knowledge
  module Books
    class BookForm
      Book: Class[Books::Book]

      attr_reader record: Book

      def save: -> bool

      def update: (untyped) -> bool

      private

      def attributes_for_model: -> Hash[Symbol, untyped]
    end
  end
end
