module Scriptures
  module Verses
    module Controllers
      class VersesController
        # Shorthands for class singletons
        Verse: Class[Models::Verse]
        VerseCreatorService: Class[Services::VerseCreatorService]
        VerseForm: Class[Forms::VerseForm]

        @verses: Array[Models::Verse]
        @verse: Models::Verse

        def index: -> void
        def show: -> void
        def create: -> void
        def update: -> void
        def destroy: -> void

        private

        def permitted_params: -> untyped

        def verse_params: -> untyped
      end
    end
  end
end