module Knowledge
  module Books
    class Book < ::ApplicationRecord
      def self.table_name: -> String
      def title: -> String?
      def title=: (String) -> String
      def author: -> String?
      def author=: (String) -> String
      def publication_date: -> Date?
      def publication_date=: (Date) -> Date
    end
  end
end
