module Knowledge
  module Books
    class BooksController < ::ApplicationController
      Book: Class[Books::Book]
      CreateBook: Class[Books::CreateBook]

      def index: -> void

      def show: -> void

      def create: -> void

      def update: -> void

      def destroy: -> void

      private

      def permitted_params: -> ActionController::Parameters
    end
  end
end
